env:
  browser: true
  es6: true
  node: true
extends:
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  prefer-arrow-callback: ['error', { 'allowNamedFunctions': true }]
  semi: ['error', 'always']
  space-before-function-paren:
    [
      'error',
      { 'anonymous': 'always', 'named': 'never', 'asyncArrow': 'always' },
    ]
  guard-for-in: 'error'
